### ISSUE TITLE
TypeError: Error #1006: value is not a function

### ISSUE THREAD

**Issue by sumowrestler** [robertpenner/as3-signals#71]
Upgraded to latest flex/flash/air libraries and game now fails with:

```
TypeError: Error #1006: value is not a function.
	at MethodInfo-1448()
	at org.osflash.signals::Slot/execute()
	at org.osflash.signals::OnceSignal/dispatch()

```
 flex=4.15.0/flash=20.0

Any help appreciated.

**Comment by SimonRichardson** [comment]
Any chance of running that in a debug player (not even sure that exists?) to get some more info, it's really limited information and I no longer use flash, but could help if I had more.

**Comment by sumowrestler** [comment]
Thanks @SimonRichardson - Was an issue in my listener code, all sorted now.
